CREATE TABLE Subjects
(
	SubjectID INT PRIMARY KEY IDENTITY,
	SubjectName VARCHAR(50) NOT NULL
)

CREATE TABLE Majors
(
	MajorID INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(50) NOT NULL
)

CREATE TABLE Students
(
	StudentID INT PRIMARY KEY IDENTITY,
	StudentNumber INT NOT NULL,
	StudentName VARCHAR(50) NOT NULL,
	MajorID INT
	CONSTRAINT FK_Students_Major_ID
	FOREIGN KEY (MajorID)
	REFERENCES Majors(MajorID)
)

CREATE TABLE Payments
(
	PaymentsID INT PRIMARY KEY IDENTITY,
	PaymentDate DATE NOT NULL,
	PaymentAmount DECIMAL (15, 2) NOT NULL,
	StudentID INT
	CONSTRAINT FK_Payments_Student_ID
	FOREIGN KEY (StudentID)
	REFERENCES Students(StudentID)
)

CREATE TABLE Agenda
(
	StudentID INT ,
	SubjectID INT,

	CONSTRAINT FK_Agend_Student_ID
	FOREIGN KEY (StudentID)
	REFERENCES Students(StudentID),

	CONSTRAINT FK_Agend_Subject_ID
	FOREIGN KEY (SubjectID)
	REFERENCES Subjects(SubjectID),

	PRIMARY KEY (StudentID, SubjectID)
)